import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About/About'
import Cta from '../components/Cta/Cta'
import Features from '../components/Features/Features'
import Footer from '../components/Footer/Footer'
import Header from '../components/header/Header'
import HeroSection from '../components/heroSection/HeroSection'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <HeroSection/>
      <Features/>
      <About/>
      <Cta/>
      <Footer/>
    </div>
  )
}
